[project]
name = "elfin-robot-ros2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "catkin-pkg>=1.1.0",
    "colcon-common-extensions>=0.3.0",
    "empy==3.3.4",
    "lark>=1.3.1",
    "numpy>=1.24.4",
    "transforms3d>=0.4.2",
]
